
(function($,HP,HF){var currentDomain=function(){var scripts=document.getElementsByTagName('script'),src,link,domain;for(var a=0;a<scripts.length;a++){src=scripts[a].src.toLowerCase();if(src.indexOf('hf-init')>0)
link=src.split('/');}
domain=link[0]+'//'+link[2]+'/';domain=domain.replace("www.www8-hp.com","www8.hp.com");return domain;};HP.caasDomain=HP.caasDomain||currentDomain();var readCookie=function(name){if(!name)return;if(document.cookie&&document.cookie!=''){var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var c=$.trim(cookies[i]);if(c.indexOf(name+'=')==0){return decodeURIComponent(c.substring(name.length+1));}}}
return null;};var getWebSectionId=function(){var metatags=document.getElementsByTagName('meta');for(i=0;i<metatags.length;i++){if(metatags[i].getAttribute('name')=='web_section_id'){return metatags[i].getAttribute('content').split(' ')[0];}}};var showLadybug=function(){var jumpID='in_rm_'+getWebSectionId()+'_ww_en_l_all_ladybug-cs';var ahref='https://external1.collaboration.hp.com/external/SPRInt_1/Lists/Service%20List%20Global%20Content%20Support/CreateForm.aspx?URL=';ahref+=escape(window.location)+'&amp;jumpid='+jumpID+'&amp;REFERRER=';if(document.referrer&&document.referrer!=''){ahref=ahref+escape(document.referrer.substr(0,1000));}
var lbtbl=" <div class='hp_employees_container'> ";lbtbl+=" <a title='HP employees: Report website issues' name='1234A' tabindex='915' class='link_metrics' href='";lbtbl+=ahref+"' target='_blank'  onmouseover=self.status='";lbtbl+=ahref+"' onmouseout=self.status=''>HP employees: Report website issues</a> ";lbtbl+=" </div> ";document.getElementById('ladybug').innerHTML=lbtbl;};var ladyBugInit=function(params,path){if(typeof(ladybugLoaded)==='undefined'){ladybugLoaded=true;var defaultParams={countryCode:"ie",languageCode:"en"};var p=$.extend(defaultParams,params);var lb=readCookie("HP_LB");$('#footer .footer_container').after('<div id="ladybug" />');if(!lb){$.getScript(HP.caasDomain+p.countryCode+"/"+p.languageCode+path).done(function(){if(OAS_AD_LADYBUG()==1){showLadybug();}});}else if(lb==1){showLadybug();}}};HP.Utils=HP.Utils||{ready:function(){}};HP.hfInit=function(params){var defaultParams={};var p=$.extend(defaultParams,params);HF.Utils.ABReady(function(){var cats=[];var searchBox=can.$('#searchBox');var searchContainer=searchBox.parent();initSearchBoxSliding(searchBox,searchContainer);var langInput=can.$('input[name="lang"]');var countryInput=can.$('input[name="cc"]');var language=p.languageCode||(langInput.length?langInput[0].value:'en');var country=p.countryCode||(countryInput.length?countryInput[0].value:'ie');var autocompleteParams=p.autocompleteParams;for(var i=0;i<autocompleteParams.length;i++){autocompleteParams[i].url=autocompleteParams[i].url.replace(/&amp;/g,'&');}
window.autocompleteLoader.setParams({language:language,country:country,url:p.autocompleteURL},autocompleteParams);hfAutocompleteStart({widthElement:searchContainer});$(".header .searchSubmit").val(rtl?"\uf020":"\uf021");initSkipLinks();HF.Control.init(HF.TopMenu,'.js_header_topmenu .selectable');HF.Control.init(HF.ShoppingWidget,'.js_shopping_widget');HF.Control.init(HF.InputPrompt,'.searchBox',{activeClass:''});HF.Control.init(HF.CountrySelector,'.js_cselector',{url:p.countrySelectorURL,requestType:'jsonp'});initHFMetrics('.link_metrics');window.initHFMetrics=function(){};ladyBugInit(p,"/caas/3.0/ladybug.jsp");HP.HF_IS_READY=true;});};})(can.$,window.HP||(window.HP={}),window.HF||(window.HF={}));

/*
Date: 5/18/2015 10:31:31 AM
All images published
*/